#!/usr/bin/env bash

set -e -o pipefail


function usage() {
  EXIT_VAL="$?"
  HELP_MSG=$(cat <<EOM
Usage: kubectl execuser [options] <podname>

  Options:
    -u|--username  <user>       : user within the pod
    -n|--namespace <namespace>  : namespace containig the pod
    -c|--container <container>  : container within the pod
    -i|--index <index>          : index of the container within the pod
    -s|--shell <shell>          : shell to exec into in the pod
    -d|--debug                  : debug mode shows the variables in the plugin
    -v|--verbose                : verbose mode
    -h|--help                   : show this help menu
EOM
  )
  if [ "$EXIT_VAL" -ne 0 ] && [ "$EXIT_VAL" -ne 130 ] || [ "$HELP" = true ] ; then
    echo "$HELP_MSG"
  fi
}

trap usage EXIT

SHORTOPTS="u:n:s:c:i:dhv"
LONGOPTS="username:namespace:shell:container:index:debug,help,verbose,"

OPTS=$(getopt -o $SHORTOPTS -l $LONGOPTS -n "$0" -- "${@}")
eval set -- "$OPTS"

VARS=$(set -o posix ; set);

POD_USER="root"
COMMAND="sh"
NAMESPACE=$(kubectl config view --minify -o 'jsonpath={..namespace}')
NAMESPACE="${NAMESPACE:-default}"
CONTAINER_INDEX=""
VERBOSE=false

while true; do
  case "$1" in
    -u | --username ) POD_USER=$2; shift 2 ;;
    -n | --namespace ) NAMESPACE=${2:-$NAMESPACE}; shift 2 ;;
    -s | --shell ) COMMAND="${2:-$COMMAND}"; shift 2 ;;
    -i | --index ) CONTAINER_INDEX=$2; shift 2 ;;
    -c | --container ) CONTAINER=$2; shift 2 ;;
    -d | --debug ) DEBUG=true; shift ;;
    -v | --verbose ) VERBOSE=true; shift ;;
    -h | --help ) HELP=true; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

POD_NAME=$1

[ "$DEBUG" = true ] &&
  grep -vFe "$VARS" <<<$(unset VARS HELP_MSG; set +e; set -o posix; set) | awk -e '{print "[\033[94mINFO\033[0m]", $0}'

[ "${HELP:-false}" = true ] &&
  exit 0

[ "${VERBOSE:-false}" = true ] &&
  set -x

[ -z "$POD_NAME" ] &&
  echo -e "[\e[91mERROR\e[0m] Podname missing!" &&
  exit 1

POD_JSON="$(kubectl get pod -n $NAMESPACE $POD_NAME -o json)"
CONTAINERS="$(echo "$POD_JSON" | jq -r '.status.containerStatuses[].name')"
NUM_CONTAINERS=$(echo "$CONTAINERS" | wc -l)

if   [ "$NUM_CONTAINERS" -gt 1 ] && [ -z "$CONTAINER_INDEX" ] && [ -z "$CONTAINER" ] \
  || [ "$DEBUG" = true ]; then
    echo -e "[\e[94mINFO\e[0m] Check help for container selection. Default container index 0."
    echo "$CONTAINERS" | awk '{printf "%8d) %s\n", line++, $0}'
fi

EXECUSER_POD="execuser-${POD_NAME}"
EXECUSER_POD=${EXECUSER_POD:0:63}  # Truncate to 64 char

if [ -z "$CONTAINER" ]; then
  DOCKER_CONTAINER_ID=$(echo "$POD_JSON" | jq -r ".status.containerStatuses[${CONTAINER_INDEX:-0}].containerID" )
else
  DOCKER_CONTAINER_ID=$(echo "$POD_JSON" | jq -r ".status.containerStatuses[] | select(.name==\"$CONTAINER\").containerID" )
fi
CONTAINER_ID=${DOCKER_CONTAINER_ID#*//}

NODENAME=$(echo "$POD_JSON" | jq -r '.spec.nodeName')
if [[ "$NODENAME" == *"master"* ]]; then
  MASTER_TOLERATIONS="\"tolerations\": [{ \"key\": \"node-role.kubernetes.io/master\" }],"
fi

CONTAINER_SPEC=$(cat <<EOM
{
    "apiVersion": "v1",
    "metadata": {
        "labels": {
            "k8s-app": "${EXECUSER_POD}"
        }
    },
    "spec": {
        "containers": [
            {
                "image": "docker",
                "name": "docker",
                "stdin": true,
                "stdinOnce": true,
                "tty": true,
                "restartPolicy": "Never",
                "resources": {
                    "limits": {
                        "cpu": "500m",
                        "memory": "50Mi"
                    },
                    "requests": {
                        "cpu": "0",
                        "memory": "0"
                    }
                },
                "args": [
                  "exec",
                  "-it",
                  "-u",
                  "${POD_USER}",
                  "${CONTAINER_ID}",
                  "${COMMAND}"
                ],
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/docker.sock",
                        "name": "docker"
                    }
                ]
            }
        ],
        "nodeSelector": {
          "kubernetes.io/hostname": "${NODENAME}"
        },
        ${MASTER_TOLERATIONS}
        "volumes": [
            {
                "name": "docker",
                "hostPath": {
                    "path": "/var/run/docker.sock",
                    "type": "File"
                }
            }
        ]
    }
}
EOM
)

kubectl delete pods -n ${NAMESPACE} -l k8s-app="${EXECUSER_POD}" --grace-period 0 &>/dev/null
kubectl run -n ${NAMESPACE} -it --rm --restart=Never --image=docker --overrides="${CONTAINER_SPEC}" ${EXECUSER_POD}
